### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by pathumego** [mooniak/ayanna-font#15]
- [x] Credits on `README.md`
- [x] Review Sinhala
- [x] Review Latin
- [x] Reveiw Tamil
- [x] Credits on `FONTLOG.md`
- [x] Credits on  `/features/tables.fea`
- [x] Copyright notice on Repo `READM.md`
- [x] Copyright notice on `OFL.txt`
- [x] Copyright on SFD sources
- [x] Copyright on UFO sources
- [x] Copyright on `/features/tables.fea`
- [x] Version on `FONTLOG.md`
- [x] Version on  `/features/tables.fea`
- [x] Description (Names/ Dates)
- [x] Fontlog
- [x] Check Issue Tracker for Release Milestone
- [x] Final Feature Testing
- [x] rc-1 Testing
- [x] Make final binarieries with OFL

**Comment by pathumego** [comment]
@paarandika Please add anything you think should be on the list

**Comment by pathumego** [comment]
@paarandika Can you check on the copyright notices?

**Comment by paarandika** [comment]
Why copy right on readme?

**Comment by pathumego** [comment]
Done f3df90a
